# Generated by Django 2.0.7 on 2018-07-31 12:23

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('classification', models.CharField(max_length=30, verbose_name='classification')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'details',
            },
        ),
    ]
