# Generated by Django 2.0.7 on 2018-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20180731_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
