# Generated by Django 2.0.7 on 2018-07-31 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20180731_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmodel',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
