# Generated by Django 2.0.7 on 2018-07-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_detailmodel_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmodel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='detailmodel',
            name='lon',
        ),
    ]
