# Generated by Django 2.0.7 on 2018-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
